apiVersion: v1
kind: Service
metadata:
  name: new-app-service
spec:
  selector:
    app: new-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 35.192.49.11
